### ISSUE TITLE
RC: v1.2.0

### ISSUE THREAD

**Issue by jgaehring** [farmOS/farmOS-map#82]
Right now, we have 5 PR's open:

- [ ] ~~Add WMTS tile layer #71~~
- [x] Add GeoJSON layer from object, instead of URL #76 #77
- [x] Add support for style functions #72 #78
- [ ] Integrate a snapping grid into farmOS-map #81
- [ ] Measure behavior on multiple layers #84

Perhaps we could review these and check them off as they're ready, or remove them from this list if we don't think they'll be ready for release in the near future? Are there any major changes already merged that we want to document here?

I know for Field Kit, it would be especially nice if #77 was in a tagged release so we could pin our dependency to it when we release OAuth.

@symbioquine, are you still working on #81?

**Comment by symbioquine** [comment]
@jgaehring I think https://github.com/farmOS/farmOS-map/pull/81 should be good to go - unless there's any feedback or new bugs found.

**Comment by mstenta** [comment]
Added https://github.com/farmOS/farmOS-map/issues/84 - only if it turns out to be easy...

**Comment by mstenta** [comment]
Removing #71 because there is still work to be done on that one.

**Comment by mstenta** [comment]
I merged #78 and #83 

Commented on #81 - we can follow up on that in a future release.

And I'm not going to try to fix #84 for this release either - really want to get v1.2.0 out and included in farmOS so that we are clear for a farmOS 1.5 release.
